### ISSUE TITLE
confused about the bert-multitask-learning/baseline.md

### ISSUE THREAD

**Issue by aslicedbread** [JayYip/m3tl#9]
Hi~

I'm a bit confused about the results in the baseline.md:
Does the baseline mean that we use the bert model without multi-task learning and the multitask_label_transfer_first_train mean that we use the bert model with multi-task learning?
It seems that all the results prove that the multitask_label_transfer_first_train  is not as good as  the baseline?

Hope to get your reply. Thanks a lot.

**Comment by JayYip** [comment]
Hi,

Baseline means training the problem individually and multitask means training multiple problems at the same time. Yes, multitask training is not as good as training each task individually. I have tried various tricks(please look for `# multitask` in params.py) and none of their result can dominate the baseline.

And please note that the results are outdated because I updated the tokenizer for better sequence labeling and the results are not updated. However, the conclusion holds for either tokenizer. 

I will update the results in couple days. Thanks for bringing this up!

**Comment by JayYip** [comment]
The baseline is updated. Closing the issue.

**Comment by aslicedbread** [comment]
> 
> 
> The baseline is updated. Closing the issue.

@JayYip 
Hi,
I just noticed that you have been upgraded the `baseline.md`.
The F1 value of the WeiboNER(singleTask) is 0.5735 which is 11% lower than before. (I remember that the previous F1 value was around 0.68.)
Is there any change?
Hope to get your reply, Thanks.

**Comment by JayYip** [comment]
Oops. Caught up by other things lately and didn't have time to take a deep look at the results. Now the results are strange and I spotted a bug in generating evaluation data which caused severe result underestimation. 

I'll re-open the issue and fix it today. Thanks!

**Comment by JayYip** [comment]
Bug fixed and baseline updated. Closing the issue.

**Comment by OYE93** [comment]
Hi @JayYip, in Microsoft paper `mt-dnn`, they prove multi-task learning can improve the performance of bert, did you have any studies in why the multi-task is not good as single task in your proposed, or maybe there are other tricks in `mt-dnn`, thanks.
